language: ruby
sudo: false
dist: trusty
cache: bundler
addons:
  postgresql: 9.5
services:
  - postgresql
before_script:
- psql -c 'create database govuk_rails_guide_test;' -U postgres
script:
- bundle exec rails spec
